# Generated by Django 5.0.3 on 2024-03-14 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                (
                    "current_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "staff_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Administrative staff", "Administrative staff"),
                            ("Acadamic Staff", "Acadamic Staff"),
                        ],
                        max_length=1024,
                        verbose_name="Staff Role",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(default=django.utils.timezone.now)),
                (
                    "date_of_admission",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date of Join"
                    ),
                ),
                (
                    "quali",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Qualification",
                    ),
                ),
                (
                    "study_year",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="If undergoing Year",
                    ),
                ),
                (
                    "study_colleg",
                    models.CharField(
                        blank=True, max_length=1024, verbose_name="College Name"
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("Hindu", "Hindu"),
                            ("Christian", "Christian"),
                            ("Muslim", "Muslim"),
                            ("others", "others"),
                        ],
                        default="Hindu",
                        max_length=554,
                        verbose_name="Religion",
                    ),
                ),
                (
                    "community",
                    models.CharField(
                        choices=[
                            ("OC", "OC"),
                            ("BC", "BC"),
                            ("MBC", "MBC"),
                            ("ST/SC", "ST/SC"),
                            ("others", "others"),
                        ],
                        default="OC",
                        max_length=524,
                        verbose_name="Community",
                    ),
                ),
                (
                    "software_pro",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Software Proficiency"
                    ),
                ),
                (
                    "last_salary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Last Job Salary drawn"
                    ),
                ),
                (
                    "working_exp",
                    models.TextField(
                        blank=True, null=True, verbose_name="Working Experience"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="", max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default=None, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 3",
                    ),
                ),
                (
                    "taluka",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Taluk",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="District"
                    ),
                ),
                (
                    "pincode",
                    models.IntegerField(
                        blank=True, default=None, verbose_name="Pincode"
                    ),
                ),
                (
                    "passport",
                    models.ImageField(
                        blank=True,
                        upload_to="staff/certificates/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "aadhar_card",
                    models.ImageField(
                        blank=True,
                        upload_to="staff/certificates/",
                        verbose_name="Aadhar Card",
                    ),
                ),
                (
                    "degree_certificate",
                    models.ImageField(
                        blank=True,
                        upload_to="staff/certificates/",
                        verbose_name="Degree Certificate",
                    ),
                ),
                (
                    "resume",
                    models.ImageField(
                        blank=True,
                        upload_to="staff/certificates/",
                        verbose_name="Resume",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
