# Generated by Django 5.0.3 on 2024-04-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0002_alter_staff_staff_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="staff_timing",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                default="Full Time",
                max_length=1023,
                verbose_name="Staff Timing",
            ),
        ),
    ]
