# Generated by Django 5.0.3 on 2024-07-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0003_staff_staff_timing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="pincode",
            field=models.IntegerField(default=None, verbose_name="Pincode"),
        ),
    ]
