# Generated by Django 5.0.3 on 2024-03-14 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corecode", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=255,
                        verbose_name="Course Status",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        default="", max_length=1024, verbose_name="Course Full Name"
                    ),
                ),
                (
                    "course_s_name",
                    models.CharField(
                        default="", max_length=1024, verbose_name="Course Short Name"
                    ),
                ),
                (
                    "course_duration",
                    models.CharField(
                        default=None, max_length=255, verbose_name="Course Duration"
                    ),
                ),
                ("course_fee", models.IntegerField(verbose_name="Course Fee")),
            ],
        ),
        migrations.CreateModel(
            name="CourseExamModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_exams", models.ManyToManyField(to="corecode.exam")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.coursemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseBookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.ManyToManyField(to="corecode.book")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.coursemodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSubjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.coursemodel",
                    ),
                ),
                ("sub_name", models.ManyToManyField(to="corecode.subject")),
            ],
        ),
    ]
