# Generated by Django 5.0.3 on 2024-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_remove_student_class_time_student_class_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="pincode",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Pincode"
            ),
        ),
    ]
