# Generated by Django 5.0.3 on 2024-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0002_auto_20240314_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="contents",
            field=models.TextField(blank=True, null=True),
        ),
    ]
