# Generated by Django 5.0.3 on 2024-03-14 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        max_length=255,
                        verbose_name="Batch Status",
                    ),
                ),
                (
                    "batch_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Batch Id"
                    ),
                ),
                (
                    "batch_start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Batch Start Date",
                    ),
                ),
                (
                    "batch_end_date",
                    models.DateField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Batch End Date",
                    ),
                ),
            ],
            options={
                "ordering": ["-batch_start_date"],
            },
        ),
    ]
