# Generated by Django 5.0.3 on 2024-03-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0002_auto_20240314_1741"),
        ("enquiry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enquiry",
            name="time_to_study",
        ),
        migrations.AddField(
            model_name="enquiry",
            name="time_to_study",
            field=models.ManyToManyField(blank=True, null=True, to="corecode.time"),
        ),
    ]
