# Generated by Django 5.0.3 on 2024-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0002_auto_20240314_1741"),
        ("enquiry", "0002_remove_enquiry_time_to_study_enquiry_time_to_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="time_to_study",
            field=models.ManyToManyField(blank=True, to="corecode.time"),
        ),
    ]
