# Generated by Django 5.0.3 on 2024-03-19 12:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0002_auto_20240314_1741"),
        ("course", "0001_initial"),
        ("enquiry", "0003_alter_enquiry_time_to_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="pincode",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Pincode"
            ),
        ),
        migrations.CreateModel(
            name="StudentEnquiryModel",
            fields=[
                ("auto_increment", models.AutoField(primary_key=True, serialize=False)),
                (
                    "enquiry_no",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Enquiry Number",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=255, verbose_name="Name"),
                ),
                (
                    "f_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="Father Name"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default=None, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 2",
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Address Line 3",
                    ),
                ),
                (
                    "taluka",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Taluk",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="District"
                    ),
                ),
                (
                    "pincode",
                    models.IntegerField(
                        blank=True, default=None, verbose_name="Pincode"
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Entered mobile number isn't in a right format!",
                                regex="^[0-9]{10,15}$",
                            )
                        ],
                        verbose_name="Mobile Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("others", "others"),
                        ],
                        default="male",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "student_role",
                    models.CharField(
                        choices=[
                            ("Employed", "Employed"),
                            ("Unemployed", "Unemployed"),
                            ("Housewife", "Housewife"),
                            ("Businessman", "Businessman"),
                            ("Student", "Student"),
                            ("Others", "Others"),
                        ],
                        default="Student",
                        max_length=1024,
                        verbose_name="Occupation",
                    ),
                ),
                (
                    "student_company_name",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="If Emloyed Company Name",
                    ),
                ),
                (
                    "qualification",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="Qualification"
                    ),
                ),
                (
                    "qualification_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Undergoing", "Undergoing"),
                            ("others", "others"),
                        ],
                        default="Completed",
                        max_length=50,
                        verbose_name="Qualification Status",
                    ),
                ),
                (
                    "studying_year",
                    models.IntegerField(
                        default=None, null=True, verbose_name="Current year"
                    ),
                ),
                (
                    "studying_course",
                    models.TextField(
                        blank=True, default="", max_length=255, verbose_name="Major"
                    ),
                ),
                (
                    "student_college_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1055,
                        null=True,
                        verbose_name="School/College Name",
                    ),
                ),
                (
                    "need_of_study",
                    models.CharField(
                        choices=[
                            ("For a job", "For a job"),
                            (
                                "For a job in software profession",
                                "For a job in software profession",
                            ),
                            ("For advance study", "For advance study"),
                            ("Sponsored by company", "Sponsored by company"),
                            ("others", "others"),
                        ],
                        default="For a job",
                        max_length=1024,
                        verbose_name="Reason for Study",
                    ),
                ),
                (
                    "known_csc",
                    models.CharField(
                        choices=[
                            ("Television", "Television"),
                            ("Newspaper", "Newspaper"),
                            ("Friend recommend", "Friend recommend"),
                            ("Poster", "Poster"),
                            ("others", "others"),
                        ],
                        default="Newspaper",
                        max_length=1024,
                        verbose_name="How You Know about CSC",
                    ),
                ),
                (
                    "new_course",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        null=True,
                        verbose_name="Others",
                    ),
                ),
                ("enquiry_date", models.DateField(default=django.utils.timezone.now)),
                ("verfied", models.BooleanField(default=False)),
                (
                    "course_to_join",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursemodel",
                    ),
                ),
                (
                    "time_to_study",
                    models.ManyToManyField(blank=True, to="corecode.time"),
                ),
            ],
        ),
    ]
