# Generated by Django 5.0.3 on 2024-03-19 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0004_alter_enquiry_pincode_studentenquirymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenquirymodel",
            name="enquiry_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="studentenquirymodel",
            name="studying_year",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Current year"
            ),
        ),
    ]
