# Generated by Django 5.0.3 on 2024-03-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0006_alter_studentenquirymodel_pincode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enquiry",
            name="studying_year",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Current year"
            ),
        ),
    ]
