# Generated by Django 5.0.3 on 2024-03-20 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0007_alter_enquiry_studying_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="alternate_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Alternate Mobile Number",
            ),
        ),
        migrations.AddField(
            model_name="studentenquirymodel",
            name="alternate_mobile_number",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Alternate Mobile Number",
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="address",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="district",
            field=models.CharField(default="", max_length=255, verbose_name="District"),
        ),
        migrations.AlterField(
            model_name="studentenquirymodel",
            name="address",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="studentenquirymodel",
            name="district",
            field=models.CharField(default="", max_length=255, verbose_name="District"),
        ),
    ]
