# Generated by Django 5.0.3 on 2024-03-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0008_enquiry_alternate_mobile_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentenquirymodel",
            name="studying_course",
            field=models.TextField(
                blank=True, default="", max_length=255, null=True, verbose_name="Major"
            ),
        ),
    ]
